[package]
name = "persister"
version = "0.1.0"
edition = "2024"

[dependencies]
rusqlite = { version = "0.38.0", features = ["fallible_uint"] }
parser = { path = "../parser" }
enricher = { path = "../enricher" }
