[package]
name = "enricher"
version = "0.1.0"
edition = "2024"

[dependencies]
parser = { path = "../parser" }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.148"
ureq = { version = "3.1.4", features = ["json"] }
